services:
  backapp:
    build:
      context: './back'
      dockerfile: Dockerfile
    container_name: 'backapp'
    deploy:
      # 자원 정책
      resources:
        limits:
          memory: '1G'
        reservations:
          cpus: '1'
    volumes:
      - ./back/src:/back/src
      - ./back/.env:/back/.env
    env_file:
      - './back/.env'
    environment:
      - TZ=Asia/Seoul
    ports:
      - '3001:3000'

  frontapp:
    build:
      context: './front'
      dockerfile: Dockerfile
    container_name: 'frontapp'
    volumes:
      - ./front/src:/front/src
      - ./front/public:/front/public
      - ./front/.env:/front/.env
    env_file:
      - './front/.env'
    environment:
      - TZ=Asia/Seoul
    ports:
      - '5173:5173'
    
  kobert:
    image: 'snghyun/ai2'
    container_name: 'kobert'
    volumes:
      - ./back:/app/back
    command: python /app/back/src/ai/app.py
    ports:
      - '3003:5000'
  stable:
    image: 'snghyun/ai2'
    container_name: 'stable'
    volumes:
      - ./back:/app/back
    command: python /app/back/src/ai/app3.py
    ports:
      - '3004:5002'

